import logging
from uuid import UUID

from app.sql.executor import SQLExecutor
from app.sql.guard import SQLGuardError

logger = logging.getLogger(__name__)


class SQLTool:
    """
    Executes a SQL query generated by the planner.
    Returns structured results or an error dict.
    """

    def __init__(self, executor: SQLExecutor, tenant_id: UUID) -> None:
        self._executor = executor
        self._tenant_id = tenant_id

    def run(self, query: str) -> dict:
        try:
            rows = self._executor.execute(query, tenant_id=self._tenant_id)
            return {"success": True, "rows": rows, "row_count": len(rows)}
        except SQLGuardError as exc:
            logger.warning("SQLGuard blocked query: %s", exc)
            return {"success": False, "error": f"Query not permitted: {exc}", "rows": []}
        except RuntimeError as exc:
            logger.error("SQL execution error: %s", exc)
            return {"success": False, "error": str(exc), "rows": []}
